version: 0.2
phases:
  # install:
  #   commands:
  build:
    commands:
      - git clone "https://github.com/Tarini-27/tarini_website.git"
      - cd tarini_website
      - file_name=$(git diff --name-only HEAD^)
      - name=$(echo $file_name)
      - echo $name
      - name1=$name
      - export name1
  post_build:
    commands:
      - python update.py
 
artifacts:
  type: zip
    files:
      **/**

